version: "3.7"

services:
    pgadmin:
      image: dpage/pgadmin4
      ports:
        - "30001:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: test
        PGADMIN_DEFAULT_PASSWORD: test
      logging:
        driver: none
  
    db:
      image: postgres
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_DB: glyphdb
        TZ: Europe/Bucharest
        PGTZ: Europe/Bucharest
      ports:
        - "54321:5432"
      volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
